name: Auto update configs

on:
  push:
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update configs
    - env: 
        gitpassword: ${{ secrets.gitpassword }}
      run: |
        apt install dos2unix
        wget https://raw.githubusercontent.com/Aefer/smartdns-Android/master/configupdate.sh && chmod 755 configupdate.sh
        ./configupdate.sh
