name: Auto update configs

on:
  push:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update configs
      run: |
        sudo apt -y install dos2unix
        cd ~/work/smartdns-Android/smartdns-Android
        chmod 755 configupdate.sh
        ./configupdate.sh
        mv -f /tmp/smartdns/* config/configs/
        rm -f config/configs/gfwlist.conf config/configs/hosts_ipv6_lennylxx

    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: $\{{ secrets.GITHUB_TOKEN }}
