name: Auto update configs

on:
  push:
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update configs
      env: 
        gitpassword: ${{ secrets.gitpassword }}
      run: |
        sudo apt -y install dos2unix
        cd ~/work/smartdns-Android
        ls -al
        ./configupdate.sh
        mv -f /tmp/smartdns/ config/configs
        git commit -c "Configs update"
        git push
