name: Auto update configs

on:
  schedule:
    - push:
    - cron:  '0 0 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update configs
      env: 
        gitpassword: ${{ secrets.gitpassword }}
      run: |
        sudo apt -y install dos2unix
        wget https://raw.githubusercontent.com/Aefer/smartdns-Android/master/configupdate.sh && chmod 755 configupdate.sh
        ./configupdate.sh
        cd ~/work/smartdns-Android
        rm -rf config/configs
        ls -al /tmp
        mv -f /tmp/smartdns config/configs
        git commit -c "Configs update"
        #echo $gitpassword > ~/.gitpassword
        git push
