name: Auto update configs

on:
  push:
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update configs
      env: 
        gitpassword: ${{ secrets.gitpassword }}
        username: ${{ secrets.username }}
        email: ${{ secrets.email }}
      run: |
        sudo apt -y install dos2unix
        cd ~/work/smartdns-Android/smartdns-Android
        chmod 755 configupdate.sh
        ./configupdate.sh
        mv -f /tmp/smartdns/ config/configs
        echo $gitpassword > ~/.git-credentials
        git config --global user.email $email
        git config --global user.name $username
        git add *
        git commit -m "Configs update"
        git push
